### ISSUE TITLE
Error on makepkg

### ISSUE THREAD

**Issue by stefanocog** [RaymiiOrg/securecrt-arch-linux#1]
Hi, i have clone the repo, cd into and launch: makepkg -si

==> Build package: securecrt 7.3.5-1 (mon 7 mar 2016, 15.21.33, CET)
==> Check dependencies in progress...
==> Check dependencies during compile in progress...
==> Source download in progress...
==> ERROR Could not find securecrt-7.3.5.903.ubuntu13-64.tar.gz to compile directory and is not a URL

**Comment by RaymiiOrg** [comment]
as said in the readme, you need to provide the binaries yourself.
